### ISSUE TITLE
What is help_query_gpu.txt for?

### ISSUE THREAD

**Issue by seibert** [gpuopenanalytics/pynvml#1]
I'm excited to see this library being revived!

The `help_query_gpu.txt` file seems to actually be a tar.gz file containing:
```
pynvml/nvidia_smi.py
pynvml/PKG-INFO
pynvml/pynvml.py
pynvml/README.txt
pynvml/setup.py
```
What is this file for, and why is it included in the package data list in setup.py?

**Comment by kenhester** [comment]
The file was corrupt and replaced.  The file provides a text response for the --help_guery_gpu .

To Run:
$ python nvidia_smi.py "--help"
$ python nvidia_smi.py "--help_query_gpu"

From Code:
DeviceQuery("--help")
DeviceQuery("--help_query_gpu")

XmlDeviceQuery("--help")
XmlDeviceQuery("--help_query_gpu")

**Comment by seibert** [comment]
Ah, that makes sense.  Thanks!
