### ISSUE TITLE
Build multi-figure dashboard 

### ISSUE THREAD

**Issue by mrocklin** [gpuopenanalytics/pynvml#10]
In https://github.com/rjzamora/jupyterlab-bokeh-server/tree/pynvml @rjzamora has a Bokeh server with several individual pages, each with a single full-page figure.  These pages were designed to be embedded into JupyterLab.  

Some consumers of this information may not want to use JupyterLab (for example, all of the CUDA programmers out there) and so we may also want to have a more dashboardy page that includes several plots laid out nicely.  I imagine that this might increase the use of these dashboards.  

This requires someone to take a look at the plots that we currently have and then arrange them nicely onto the page using either [Bokeh layout](https://bokeh.pydata.org/en/latest/docs/reference/layouts.html), or just standard HTML/CSS.  

cc @jacobtomlinson, you might find this interesting to get your feet wet with GPU things.

**Comment by rjzamora** [comment]
Sounds good @mrocklin -  Note that I was about to do this in the `layout` branch of `pynvlm`.  However, I only added some rough NvLink plots and got distracted by other things.   I am happy to chat with @jacobtomlinson to describe what has/hasn't been done :)

**Comment by jacobtomlinson** [comment]
This work is now in [jupyterlab-nvdashboard](https://github.com/jacobtomlinson/jupyterlab-nvdashboard) and it might make sense to move this discussion to rapidsai/jupyterlab-nvdashboard#20.
