### ISSUE TITLE
Bump version in __init__ to 8.0.2

### ISSUE THREAD

**Issue by jakirkham** [gpuopenanalytics/pynvml#11]
Currently [this is `8.0.1`]( https://github.com/gpuopenanalytics/pynvml/blob/0f3d62fee608862faeecba854455911e668ff84b/pynvml/__init__.py#L3 ). Would be good to bump to 8.0.2 to match the tag.

**Comment by jakirkham** [comment]
Also to avoid this sort of issue here in the future, we could consider using versioneer ( https://github.com/gpuopenanalytics/pynvml/issues/12 ).

**Comment by rjzamora** [comment]
Thanks @jakirkham!   I can't believe I missed this :/   I'll definitely look into versioneer :)

**Comment by jakirkham** [comment]
I think @jacobtomlinson also has some experience using it.
