### ISSUE TITLE
NVLINK Ask

### ISSUE THREAD

**Issue by quasiben** [gpuopenanalytics/pynvml#17]
I am interested in two nvlink capabilities I call from the command line:

- nvidia-smi nvlink -g 1 -i 2
  - I believe the above asks for the total data transferred with counter 1 on GPU 2 (note: there are two counters 1 and 0)

- nvidia-smi nvlink -r 1
 - This call resets all the counters of type `1` on all GPUs

Could these call be exposed to pynvml ?

cc @thomcom @shwina

**Comment by quasiben** [comment]
Could some of this be done with `DeviceQuery()` ?

**Comment by rjzamora** [comment]
You might find [the nvlink nvdashboard](https://github.com/jacobtomlinson/jupyterlab-nvdashboard/blob/c985bcbf572e939f17cb206a2c2eda4ac56ab865/jupyterlab_nvdashboard/apps/gpu.py#L192) code to be a useful reference for what is already available in pynvml (regarding NVML wrappers).  The `nvlink` keyword is not yet available for the smi wrappers, but it *probably* can be exposed (I haven't personally looked into this yet)

**Comment by quasiben** [comment]
Thank you!

> pynvml.nvmlDeviceGetNvLinkUtilizationCounter(handles[0], 0, 1) 

I think the above is exactly what i need

**Comment by rjzamora** [comment]
Yup -  `nvidia-smi nvlink -g 1 -i 2` (for single link):

```python
In [1]: import pynvml
   ...: pynvml.nvmlInit()
   ...: gpu_handle = pynvml.nvmlDeviceGetHandleByIndex(2)  # -i 2
   ...: counter = 1 # -g 1
   ...: link = 0
In [5]: pynvml.nvmlDeviceGetNvLinkUtilizationCounter(gpu_handle, link, counter)                                                                                                          
Out[5]: {'rx': 0, 'tx': 0}
```

**Comment by rjzamora** [comment]
> I think the above is exactly what i need

One warning:  Take note of [the subprocess nvidia-smi](https://github.com/jacobtomlinson/jupyterlab-nvdashboard/blob/c985bcbf572e939f17cb206a2c2eda4ac56ab865/jupyterlab_nvdashboard/apps/gpu.py#L210) call used in nvdashboard.  I could not figure out how to set the the output of `nvmlDeviceGetNvLinkUtilizationCounter` to be in "bytes" without using this command first (the pynvml wrappers seem to be missing the functionality?).

**Comment by quasiben** [comment]
Thanks @rjzamora this is super helpful!

**Comment by quasiben** [comment]
@rjzamora, Do you know why there might be a mismatch in reporting from the CLI tool and pyvnml.  For example, with the CLI tool;

```
(cudf-dev) bzaitlen@dgx15:~/$ nvidia-smi nvlink -g 1 -i 0
GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-96ab329d-7a1f-73a8-a9b7-18b4b2855f92)
         Link 0: Rx1: 0 KBytes, Tx1: 0 KBytes
         Link 1: Rx1: 0 KBytes, Tx1: 98 KBytes
         Link 2: Rx1: 0 KBytes, Tx1: 0 KBytes
         Link 3: Rx1: 0 KBytes, Tx1: 0 KBytes
         Link 4: Rx1: 0 KBytes, Tx1: 0 KBytes
         Link 5: Rx1: 0 KBytes, Tx1: 0 KBytes
```

With `pynvml`
```
In [12]: for i in range(nlinks):
    ...:     print(i, pynvml.nvmlDeviceGetNvLinkUtilizationCounter(handles[0], i, 1))
    ...:
0 {'rx': 0, 'tx': 0}
1 {'rx': 0, 'tx': 0}
2 {'rx': 0, 'tx': 0}
3 {'rx': 0, 'tx': 0}
4 {'rx': 0, 'tx': 0}
5 {'rx': 0, 'tx': 0}
```

**Comment by rjzamora** [comment]
@quasiben - Thanks for sharing this! I can confirm that I don't get the `98 KBytes`:

**nvidia-smi (CLI)**:
```
$ nvidia-smi nvlink -g 1 -i 0
GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-96ab329d-7a1f-73a8-a9b7-18b4b2855f92)
         Link 0: Rx1: 3422552 KBytes, Tx1: 3422552 KBytes
         Link 1: Rx1: 0 KBytes, Tx1: 98 KBytes
         Link 2: Rx1: 0 KBytes, Tx1: 0 KBytes
         Link 3: Rx1: 0 KBytes, Tx1: 0 KBytes
         Link 4: Rx1: 0 KBytes, Tx1: 0 KBytes
         Link 5: Rx1: 0 KBytes, Tx1: 0 KBytes
```

**pynvml**:
```python
In [8]: for i in range(nlinks): 
   ...:     ...:     print(i, pynvml.nvmlDeviceGetNvLinkUtilizationCounter(handle, i, 1)) 
   ...:                                                                                                                     
0 {'rx': 3422552064, 'tx': 3422552064}
1 {'rx': 0, 'tx': 0}
2 {'rx': 0, 'tx': 0}
3 {'rx': 0, 'tx': 0}
4 {'rx': 0, 'tx': 0}
5 {'rx': 0, 'tx': 0}
```

**Comment by rjzamora** [comment]
Ahh - [definitely a bug](https://github.com/gpuopenanalytics/pynvml/blob/8011118249832d30095e76f507df6c8934ade059/pynvml/nvml.py#L2000) - I'll submit a bugfix.  Thanks again for sharing @quasiben !

**Comment by quasiben** [comment]
Thanks for all the help @rjzamora
