### ISSUE TITLE
MIG Support

### ISSUE THREAD

**Issue by PidgeyBE** [gpuopenanalytics/pynvml#30]
Dear

Pynvml is not in sync anymore with nvml. More specifically it is not possible to access the MIG APIs: https://docs.nvidia.com/deploy/nvml-api/group__nvmlMultiInstanceGPU.html#group__nvmlMultiInstanceGPU_1g15e07cc6230a2d90c5bc85de85261ef7

Would it be possible to add these?

BR, Pieterjan

**Comment by quasiben** [comment]
It's something we should add.  I don't know how soon this can get done. @kenhester do you have any time to work on this ?  If not, no worries.

**Comment by kenhester** [comment]
I am working on sync'ing pynvml with nvml.  I have sync'd the headers up to CUDA 11. I will work to timely implement the API changes, enhancements, and updates.

**Comment by kenhester** [comment]
To answer directly, MIG support is a target feature to implement.

**Comment by kenhester** [comment]
MIG functionality is being added to my branch. There are more functions to be implemented, but comments and issues welcome.

**Comment by zronaghi** [comment]
cc @drobison00

**Comment by rjzamora** [comment]
Note that #32 includes some MIG support.  However, I do not personally have the proper resources for testing.

**Comment by zronaghi** [comment]
Thanks @rjzamora, we can test once it's ready.

**Comment by kenhester** [comment]
The bindings are updated. Please confirm it addresses your issue.

**Comment by rjzamora** [comment]
The LocalCUDACluster bug will probably require a Dask-CUDA fix (since I believe MIG requires a slightly different NVML API)

**Comment by pentschev** [comment]
MIG support is in, so I think this can be closed. The `LocalCUDACluster` issue is being discussed in https://github.com/rapidsai/dask-cuda/issues/583 , and it seems that all NVML features required for that are available in latest PyNVML releases.
