### ISSUE TITLE
Readme.md import example

### ISSUE THREAD

**Issue by zansity** [gpuopenanalytics/pynvml#41]
Hello,

From the example to import the module (`from pynvml import *`) should be `import pynvml` or to import a specific function or subclass for best Python coding practices. 

The phrase `from module import *` can cause namespace collisions within people's code and should be avoided whenever it can.

**Comment by rjzamora** [comment]
Agree that `import *` should be discouraged. If I understand correctly, the "example" actually predates this repository. Are you interested in submitting a PR to improve this?

**Comment by zansity** [comment]
Of course! Thank you.
