### ISSUE TITLE
Create conda recipe on conda forge

### ISSUE THREAD

**Issue by mrocklin** [gpuopenanalytics/pynvml#7]
See https://conda-forge.org/#contribute

@rjzamora can you take a look at doing this?  My hope is that the docs above make it somewhat straightforward.  Either @quasiben or @jakirkham should be able to help if things get complex (which wouldn't be surprising).

**Comment by rjzamora** [comment]
@mrocklin I put together a simple recipe, and submitted a PR (https://github.com/conda-forge/staged-recipes/pull/8286)

**Comment by rjzamora** [comment]
@quasiben @jakirkham Any idea what might be causing [this build error](https://github.com/conda-forge/staged-recipes/pull/8286/checks?check_run_id=120361432)?

**Comment by jakirkham** [comment]
Sorry I missed this. Probably some issue between Azure and GitHub talking to each other. Not too much that we can do beyond raising it to the service providers (though usually they pick up on these issues pretty quick without our help). Sounds like it went away anyways.

**Comment by jakirkham** [comment]
Closing as this appears to be resolved. Though please reopen if that is not the case. Thanks for working on this Rick!
