### ISSUE TITLE
Add `nvmlDeviceGetNvLink*` function wrappers

### ISSUE THREAD

**Issue by rjzamora** [gpuopenanalytics/pynvml#8]
As pointed out to me by @mt-jones, the NVML C API currently provides NvLink functions, like [`nvmlDeviceGetNvLinkUtilizationCounter`](https://docs.nvidia.com/deploy/nvml-api/group__NvLink.html#group__NvLink_1gd623d8eaf212205fd282abbeb8f8c395). 

PyNVML wrappers for these functions would be useful to multi-GPU users.

**Comment by mrocklin** [comment]
Thanks for the pointer @mt-jones !

**Comment by mrocklin** [comment]
Was this fixed by https://github.com/gpuopenanalytics/pynvml/pull/9 ?

**Comment by rjzamora** [comment]
@mrocklin Yes, this can be closed.  However, the `nvmlDeviceSetNvLinkUtilizationControl` function (and maybe others) may need to be improved in the future.   That is, I am curently using an `nvidia-smi` [system call](https://github.com/rjzamora/jupyterlab-bokeh-server/blob/e1d69629613ae0f1afea85c978ffbf1bd968d1cd/jupyterlab_bokeh_server/nvml_apps.py#L81) to produce a rough bokeh plot for NvLink usage.  I would like to be able to use pure pynvml.  The problem may be that the `nvmlNvLinkUtilizationControl_t` type is currently missused.
